import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vezdekod Contest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Vezdekod Contest
        </h1>

        <p className={styles.description}>
          Для того, чтобы начать создавать турнир, нужно перейти по пути /{'<произвольный id>'}. Например, <a href="./2" className={styles.link}>сюда</a>.
          Можно посмотреть на предзаполненный командами пример <a href="./1" className={styles.link}>вот здесь</a>.
        </p>
      </main>
    </div>
  )
}

export default Home
